
FLIGHT_API_KEY = "6lphwkBA7bskhP8ajGvwjHhTKQX2PhK8"      # Amadeus API key
FLIGHT_API_SECRET = "OS2JFA3GPTu1r7y2" # Amadeus API secret
HOTEL_API_KEY = "YOUR_HOTEL_API_KEY"
GOOGLE_API_KEY = "YOUR_GOOGLE_API_KEY"
CHATGPT_API_KEY = "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"


