
FLIGHT_API_KEY = "6lphwkBA7bskhP8ajGvwjHhTKQX2PhK8"      # Amadeus API key
FLIGHT_API_SECRET = "OS2JFA3GPTu1r7y2" # Amadeus API secret
HOTEL_API_KEY = "YOUR_HOTEL_API_KEY"
GOOGLE_API_KEY = "YOUR_GOOGLE_API_KEY"
CHATGPT_API_KEY = "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"


